plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.shenxian.promotion'
    compileSdk 34

    defaultConfig {
        applicationId 'com.shenxian.promotion'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '0.1'
    }
}
